BEGIN EXECUTE IMMEDIATE 'DROP TABLE FareObs CASCADE CONSTRAINTS'; 
EXCEPTION WHEN OTHERS THEN NULL; 
END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Fare CASCADE CONSTRAINTS'; 
EXCEPTION WHEN OTHERS THEN NULL; 
END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RouteLeg CASCADE CONSTRAINTS'; 
EXCEPTION WHEN OTHERS THEN NULL; 
END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Route CASCADE CONSTRAINTS'; 
EXCEPTION WHEN OTHERS THEN NULL; 
END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Airport CASCADE CONSTRAINTS'; 
EXCEPTION WHEN OTHERS THEN NULL; 
END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE City CASCADE CONSTRAINTS'; 
EXCEPTION WHEN OTHERS THEN NULL; 
END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Airline CASCADE CONSTRAINTS'; 
EXCEPTION WHEN OTHERS THEN NULL; 
END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Info CASCADE CONSTRAINTS'; 
EXCEPTION WHEN OTHERS THEN NULL; 
END;

CREATE TABLE Airline (
    airline_id      NUMBER GENERATED BY DEFAULT AS PRIMARY KEY,
    airline_name    VARCHAR2(100) NOT NULL UNIQUE
);

CREATE TABLE City (
    city_id     NUMBER GENERATED BY DEFAULT AS PRIMARY KEY,
    city_name   VARCHAR2(100) NOT NULL UNIQUE
);

CREATE TABLE Airport (
    airport_code    VARCHAR2(10) PRIMARY KEY,
    city_id         NUMBER NOT NULL,
    CONSTRAINT fk_airport_city
        FOREIGN KEY (city_id) REFERENCES City(city_id)
);

CREATE TABLE Route (
    route_id         NUMBER GENERATED BY DEFAULT AS PRIMARY KEY,
    source_id        VARCHAR2(10) NOT NULL,
    destination_id   VARCHAR2(10) NOT NULL,
    CONSTRAINT fk_route_source
        FOREIGN KEY (source_id) REFERENCES Airport(airport_code),
    CONSTRAINT fk_route_destination
        FOREIGN KEY (destination_id) REFERENCES Airport(airport_code),
    CONSTRAINT uq_route UNIQUE (source_id, destination_id),
);

CREATE TABLE RouteLeg (
    route_id         NUMBER NOT NULL,
    leg_number       NUMBER NOT NULL,
    source_id        VARCHAR2(10) NOT NULL,
    destination_id   VARCHAR2(10) NOT NULL,
    PRIMARY KEY (route_id, leg_number),
    CONSTRAINT fk_routeleg_route
        FOREIGN KEY (route_id) REFERENCES Route(route_id),
    CONSTRAINT fk_routeleg_source
        FOREIGN KEY (source_id) REFERENCES Airport(airport_code),
    CONSTRAINT fk_routeleg_destination
        FOREIGN KEY (destination_id) REFERENCES Airport(airport_code),
);

CREATE TABLE Fare (
    fare_id     NUMBER GENERATED BY DEFAULT AS PRIMARY KEY,
    airline_id  NUMBER NOT NULL,
    route_id    NUMBER NOT NULL,
    CONSTRAINT fk_fare_airline
        FOREIGN KEY (airline_id) REFERENCES Airline(airline_id),
    CONSTRAINT fk_fare_route
        FOREIGN KEY (route_id) REFERENCES Route(route_id),
    CONSTRAINT uq_fare UNIQUE (airline_id, route_id)
);

CREATE TABLE Info (
    info_id     NUMBER GENERATED BY DEFAULT AS PRIMARY KEY,
    info_body   VARCHAR2(200) NOT NULL UNIQUE
);

CREATE TABLE FareObs (
    obs_id              NUMBER GENERATED BY DEFAULT AS PRIMARY KEY,
    fare_id             NUMBER NOT NULL,
    info_id             NUMBER NOT NULL,
    journey_date        DATE NOT NULL,
    departure_time      VARCHAR2(20) NOT NULL,
    arrival_time        VARCHAR2(20) NOT NULL,
    arrival_day_offset  NUMBER DEFAULT 0 NOT NULL,
    duration_minutes    NUMBER NOT NULL,
    total_stops         NUMBER NOT NULL,
    price               NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_fareobs_fare
        FOREIGN KEY (fare_id) REFERENCES Fare(fare_id),
    CONSTRAINT fk_fareobs_info
        FOREIGN KEY (info_id) REFERENCES Info(info_id),
);
